// Code generated by MockGen. DO NOT EDIT.
// Source: SESRepository.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSESRepository is a mock of SESRepository interface.
type MockSESRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSESRepositoryMockRecorder
}

// MockSESRepositoryMockRecorder is the mock recorder for MockSESRepository.
type MockSESRepositoryMockRecorder struct {
	mock *MockSESRepository
}

// NewMockSESRepository creates a new mock instance.
func NewMockSESRepository(ctrl *gomock.Controller) *MockSESRepository {
	mock := &MockSESRepository{ctrl: ctrl}
	mock.recorder = &MockSESRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSESRepository) EXPECT() *MockSESRepositoryMockRecorder {
	return m.recorder
}

// GetKeyid mocks base method.
func (m *MockSESRepository) GetKeyid() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyid")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetKeyid indicates an expected call of GetKeyid.
func (mr *MockSESRepositoryMockRecorder) GetKeyid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyid", reflect.TypeOf((*MockSESRepository)(nil).GetKeyid))
}

// GetRegion mocks base method.
func (m *MockSESRepository) GetRegion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockSESRepositoryMockRecorder) GetRegion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockSESRepository)(nil).GetRegion))
}

// GetSecretkey mocks base method.
func (m *MockSESRepository) GetSecretkey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretkey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecretkey indicates an expected call of GetSecretkey.
func (mr *MockSESRepositoryMockRecorder) GetSecretkey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretkey", reflect.TypeOf((*MockSESRepository)(nil).GetSecretkey))
}
